categories = {
    "Restauracja": ["African",
                    "American (Traditional)",
                    "Arabian",
                    "Armenian",
                    "Asian Fusion",
                    "Barbeque",
                    "Belgian",
                    "Bistros",
                    "Brazilian",
                    "Breakfast & Brunch",
                    "British",
                    "Bubble Tea",
                    "Buffets",
                    "Bulgarian",
                    "Burgers",
                    "Caribbean",
                    "Chinese",
                    "Creperies",
                    "Cupcakes",
                    "Dim Sum",
                    "Diners",
                    "Falafel",
                    "Fast Food",
                    "Fish & Chips",
                    "Food",
                    "Food Stands",
                    "Food Trucks",
                    "French",
                    "Friterie",
                    "Georgian",
                    "German",
                    "Greek",
                    "Hawaiian",
                    "Himalayan/Nepalese",
                    "Hot Dogs",
                    "Hungarian",
                    "Ice Cream & Frozen Yogurt",
                    "Indian",
                    "Indonesian",
                    "International",
                    "Italian",
                    "Japanese",
                    "Jewish",
                    "Kebab",
                    "Korean",
                    "Kosher",
                    "Lebanese",
                    "Limos",
                    "Local Flavor",
                    "Mexican",
                    "Middle Eastern",
                    "Milk Bars",
                    "Modern European",
                    "Moroccan",
                    "Pan Asian",
                    "Pierogis",
                    "Pizza",
                    "Polish",
                    "Portuguese",
                    "Ramen",
                    "Restaurants",
                    "Russian",
                    "Salad",
                    "Sandwiches",
                    "Seafood",
                    "Serbo Croatian",
                    "Soup",
                    "Southern",
                    "Spanish",
                    "Sri Lankan",
                    "Steakhouses",
                    "Sushi Bars",
                    "Tapas Bars",
                    "Tapas/Small Plates",
                    "Tex-Mex",
                    "Thai",
                    "Turkish",
                    "Ukrainian",
                    "Vegan",
                    "Vegetarian",
                    "Vietnamese", "Brasseries", "Czech",
                    "Latin American",
                    "Mediterranean"],
    "Kawiarnia": ["Cafes",
                  "Cafeteria",
                  "Coffee & Tea",
                  "Desserts",
                  "Themed Cafes", ],
    "Pub": ["Bars",
            "Beer Bar",
            "Beer Gardens",
            "Cocktail Bars",
            "Gastropubs",
            "Gay Bars",
            "Hookah Bars",
            "Jazz & Blues",
            "Karaoke",
            "Music Venues",
            "Pubs",
            "Social Clubs",
            "Sports Bars",
            "Wine Bars",
            "Wineries", "Dive Bars", ],
    "Rozrywka": ["Arts & Entertainment",
                 "Cinema",
                 "Comedy Clubs",
                 "Cultural Center",
                 "Dance Clubs",
                 "Dance Studios",
                 "Escape Games",
                 "Laser Tag"],
    "Sport": ["Active Life",
              "Amateur Sports Teams",
              "Boating",
              "Bowling",
              "Climbing",
              "Go Karts",
              "Gun/Rifle Ranges",
              "Gyms",
              "Hiking",
              "Historical Tours",
              "Martial Arts",
              "Massage",
              "Mountain Biking",
              "Performing Arts",
              "Pilates",
              "Playgrounds",
              "Recreation Centers",
              "Scuba Diving",
              "Skate Parks",
              "Skating Rinks",
              "Soccer",
              "Sporting Goods",
              "Sports Clubs",
              "Squash",
              "Swimming Lessons/Schools",
              "Swimming Pools",
              "Taekwondo",
              "Tai Chi",
              "Tennis",
              "Tours",
              "Trainers",
              "Venues & Event Spaces",
              "Yoga", "Fishing",
              "Fitness & Instruction",
              "Golf",
              "Horseback Riding",
              "Karate",
              "Pool Halls",
              "Water Parks"],
    "Zoo": [
        "Aquariums", "Zoos"],
    "Transport": ["Airlines",
                  "Airport Lounges",
                  "Airports",
                  "Automotive",
                  "Bicycle Paths",
                  "Bike Rentals",
                  "Bike Repair/Maintenance",
                  "Bus Stations",
                  "Car Dealers",
                  "Car Rental",
                  "Metro Stations",
                  "Passport & Visa Services",
                  "Pest Control",
                  "Pet Stores",
                  "Public Transportation",
                  "Taxis",
                  "Train Stations",
                  "Trains",
                  "Transportation",
                  "Travel Services",
                  "Vacation Rental Agents",
                  "Vacation Rentals"],
    "Park": ["Amusement Parks",
             "Beaches",
             "Dog Parks",
             "Parks", "Lakes", "Landmarks & Historical Buildings"],
    "Sklep": ["Bakeries",
              "Bookstores",
              "Chicken Shop",
              "Convenience Stores",
              "Delis",
              "Nutritionists",
              "Public Plazas",
              "Shopping Centers",
              "Tobacco Shops",
              "Vinyl Records", "Patisserie/Cake Shop"],
    "Hotel": ["Bed & Breakfast",
              "Guest Houses",
              "Hostels",
              "Hotels",
              "Lounges"],
    "Edukacja": ["Colleges & Universities",
                 "Dance Schools",
                 "Elementary Schools",
                 "Kids Activities"],
    "Usługi": ["Photographers",
               "Professional Services",
               "Property Management"],
    "Muzeum": ["Art Museums",
               "Museums"]
}
